paths:
  input_data: "data/150_users_dataset.csv"
  app_mappings: "mappings/app_mappings_2st_round.csv"
  site_mappings: "mappings/site_mappings_3rd_round_.csv"
  browsers: "mappings/browsers.csv"
  exclude_mappings: "mappings/exclude_mappings.json"
  processed_data: "data/processed_data.csv"
